name: fff
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - pandas
  - loguru
  - face-recognition
  - pip:
      - attrs
      - opencv-python
      - tensorflow
